/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthActionRouteImport } from './routes/auth/action'
import { Route as ApiClientIpRouteImport } from './routes/api/client-ip'
import { Route as ApiArchiveRouteImport } from './routes/api/archive'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedExploreIndexRouteImport } from './routes/_authenticated/explore/index'
import { Route as AuthenticatedWatchIdRouteImport } from './routes/_authenticated/watch.$id'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person.$id'
import { Route as AuthenticatedMovieIdRouteImport } from './routes/_authenticated/movie.$id'
import { Route as AuthenticatedExploreGenreIdRouteImport } from './routes/_authenticated/explore/$genreId'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => AuthRoute,
} as any)
const ApiClientIpRoute = ApiClientIpRouteImport.update({
  id: '/api/client-ip',
  path: '/api/client-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreIndexRoute =
  AuthenticatedExploreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExploreRoute,
  } as any)
const AuthenticatedWatchIdRoute = AuthenticatedWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovieIdRoute = AuthenticatedMovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreGenreIdRoute =
  AuthenticatedExploreGenreIdRouteImport.update({
    id: '/$genreId',
    path: '/$genreId',
    getParentRoute: () => AuthenticatedExploreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/explore': typeof AuthenticatedExploreRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/auth/action': typeof AuthActionRoute
  '/explore/$genreId': typeof AuthenticatedExploreGenreIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/explore/': typeof AuthenticatedExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/auth/action': typeof AuthActionRoute
  '/explore/$genreId': typeof AuthenticatedExploreGenreIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/explore': typeof AuthenticatedExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/auth/action': typeof AuthActionRoute
  '/_authenticated/explore/$genreId': typeof AuthenticatedExploreGenreIdRoute
  '/_authenticated/movie/$id': typeof AuthenticatedMovieIdRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/_authenticated/watch/$id': typeof AuthenticatedWatchIdRoute
  '/_authenticated/explore/': typeof AuthenticatedExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/tos'
    | '/browse'
    | '/calendar'
    | '/explore'
    | '/history'
    | '/profiles'
    | '/search'
    | '/settings'
    | '/api/archive'
    | '/api/client-ip'
    | '/auth/action'
    | '/explore/$genreId'
    | '/movie/$id'
    | '/person/$id'
    | '/watch/$id'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/tos'
    | '/browse'
    | '/calendar'
    | '/history'
    | '/profiles'
    | '/search'
    | '/settings'
    | '/api/archive'
    | '/api/client-ip'
    | '/auth/action'
    | '/explore/$genreId'
    | '/movie/$id'
    | '/person/$id'
    | '/watch/$id'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/tos'
    | '/_authenticated/browse'
    | '/_authenticated/calendar'
    | '/_authenticated/explore'
    | '/_authenticated/history'
    | '/_authenticated/profiles'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/api/archive'
    | '/api/client-ip'
    | '/auth/action'
    | '/_authenticated/explore/$genreId'
    | '/_authenticated/movie/$id'
    | '/_authenticated/person/$id'
    | '/_authenticated/watch/$id'
    | '/_authenticated/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TosRoute: typeof TosRoute
  ApiArchiveRoute: typeof ApiArchiveRoute
  ApiClientIpRoute: typeof ApiClientIpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/client-ip': {
      id: '/api/client-ip'
      path: '/api/client-ip'
      fullPath: '/api/client-ip'
      preLoaderRoute: typeof ApiClientIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore/': {
      id: '/_authenticated/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof AuthenticatedExploreIndexRouteImport
      parentRoute: typeof AuthenticatedExploreRoute
    }
    '/_authenticated/watch/$id': {
      id: '/_authenticated/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AuthenticatedWatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movie/$id': {
      id: '/_authenticated/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof AuthenticatedMovieIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore/$genreId': {
      id: '/_authenticated/explore/$genreId'
      path: '/$genreId'
      fullPath: '/explore/$genreId'
      preLoaderRoute: typeof AuthenticatedExploreGenreIdRouteImport
      parentRoute: typeof AuthenticatedExploreRoute
    }
  }
}

interface AuthenticatedExploreRouteChildren {
  AuthenticatedExploreGenreIdRoute: typeof AuthenticatedExploreGenreIdRoute
  AuthenticatedExploreIndexRoute: typeof AuthenticatedExploreIndexRoute
}

const AuthenticatedExploreRouteChildren: AuthenticatedExploreRouteChildren = {
  AuthenticatedExploreGenreIdRoute: AuthenticatedExploreGenreIdRoute,
  AuthenticatedExploreIndexRoute: AuthenticatedExploreIndexRoute,
}

const AuthenticatedExploreRouteWithChildren =
  AuthenticatedExploreRoute._addFileChildren(AuthenticatedExploreRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMovieIdRoute: typeof AuthenticatedMovieIdRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
  AuthenticatedWatchIdRoute: typeof AuthenticatedWatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMovieIdRoute: AuthenticatedMovieIdRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
  AuthenticatedWatchIdRoute: AuthenticatedWatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthActionRoute: typeof AuthActionRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActionRoute: AuthActionRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TosRoute: TosRoute,
  ApiArchiveRoute: ApiArchiveRoute,
  ApiClientIpRoute: ApiClientIpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
